### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by maxmito** [twilio-infra-as-code/outbound-messaging#1]
Hello,
I'm trying this plugin and this is what I noticed:
1) after downloading it I had to upgrade the plugin via Twilio CLi (no big issue)
2) I added the accountsid in the appConfig.js file
3) I started the plugin via TwilioCli 
4) I see there is a new little form added in the DialPad section that let me insert to number and there is a "start" button, when I try it i get "Loading..." and no option to add the body and nothing else happens.

Is there any steps I'm missing?
Thanks!

Max

**Comment by kaiquelupo** [comment]
Hey @maxmito. This plugin is meant to open the chat conversation window (as it would open with an incoming message) after you hit "start".  Are you stuck on the "loading" message?

**Comment by maxmito** [comment]
Hi @kaiquelupo ,
exactly I'm stuck on the Loading message, and no chat conversation window opens.
I'm just wondering.. is there any functions to deploy as well I missed?
Thanks

**Comment by kaiquelupo** [comment]
@maxmito exactly, there are functions you need to make this work. In this [directory](https://github.com/twilio-infra-as-code/outbound-messaging/tree/main/src/serverless/main) you can find the functions. Keep in mind that this project was meant to be deployed to Twilio using Pulumi (an Infrastructure as code platform) as described [here](https://www.twilio.com/blog/intro-to-infrastructure-as-code-with-twilio-part-1). However, you don't need to use it, you can keep doing the way you are doing but make sure you are deploying the plugin and functions. Also, they need environment variables as following: 

**For the functions**:  FLEX_FLOW_SID, FLEX_PROXY_SERVICE_SID, TWILIO_PHONE_NUMBER, CHAT_SERVICE_SID, WORKSPACE_SID, WORKFLOW_SID: 
**For the plugin**: REACT_APP_SERVICE_BASE_URL (the domain of your functions)

**Comment by maxmito** [comment]
All Env Variables go in the same env file [here](https://github.com/twilio-infra-as-code/outbound-messaging/blob/main/src/flex-plugins/plugin-outbound-sms/.env)?

I set the REACT_APP_SERVICE_BASE_URL in the .env file and the other in the Env Variables within Twilio Functions Console... deployed the functions, redeployed the plugin, still same issue.

Thanks!

**Comment by maxmito** [comment]
After few attempts, upgrade, etc.. I started getting this error (at least something :)  )

TypeError: Cannot read property 'create' of undefined at /var/task/handlers/ZNXXXXXXXXXXXXXXXXXXX.js:26:14 at /var/task/node_modules/twilio-flex-token-validator/dist/index.js:125:20 at processTicksAndRejections (internal/process/task_queues.js:97:5)

on the initiate-outbound-sms function execution, it seems related to the flexApi.channel.creation step

**Comment by maxmito** [comment]
While troubleshooting the issue got this more detailed error, I confirm it's about client.flexApi.channel.create step

TypeError: Cannot read property 'create' of undefined at /var/task/handlers/ZNXXXXXXXXXXXXXXXXXXX.js:27:14 at /var/task/node_modules/twilio-flex-token-validator/dist/index.js:125:20 at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by maxmito** [comment]
@kaiquelupo any idea how to fix error above?
Thanks!

**Comment by vernig** [comment]
Hey @maxmito, please use the README here to install the solutions on project: https://github.com/twilio-infra-as-code/outbound-messaging/issues/3. 

Also, before deploying it, can you make the changes described here: https://github.com/twilio-infra-as-code/outbound-messaging/issues/4

**Comment by kaiquelupo** [comment]
@maxmito let us know if @vernig updates are enough to solve your issues.

**Comment by maxmito** [comment]
Yes with @vernig instructions I was able to make it work, it uses Pulumi as your original idea for this plugin too
